In [3]:
import numpy as np
import pandas as pd

In [4]:
df1 = pd.read_csv(r'C:\Users\user\Documents\python basic\Product.csv')

In [5]:
df1.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000566,P636635,M,36-45,14,A,0,0,18,NaN,NaN,1568
1,1000299,P651497,F,18-25,13,C,3,1,18,19.0,NaN,18750
2,1000624,P726719,F,51-55,20,B,3,1,13,NaN,11.0,2146
3,1000638,P810281,F,36-45,2,B,3,1,6,11.0,19.0,13161
4,1000518,P435830,F,55+,16,C,3,1,14,NaN,NaN,6512

In [6]:
df1.tail()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
4995,1000821,P151902,M,26-35,7,C,4+,0,5,3.0,12.0,3786
4996,1000899,P879597,F,0-17,14,B,4+,1,13,NaN,NaN,16071
4997,1000969,P852461,F,36-45,8,C,0,1,17,4.0,NaN,4449
4998,1000709,P466662,F,26-35,9,B,0,0,5,NaN,NaN,8266
4999,1000921,P833754,F,26-35,15,A,3,0,6,NaN,6.0,4794

In [7]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   User_ID                     5000 non-null   int64
 1   Product_ID                  5000 non-null   str
 2   Gender                      5000 non-null   str
 3   Age                         5000 non-null   str
 4   Occupation                  5000 non-null   int64
 5   City_Category               5000 non-null   str
 6   Stay_In_Current_City_Years  5000 non-null   str
 7   Marital_Status              5000 non-null   int64
 8   Product_Category_1          5000 non-null   int64
 9   Product_Category_2          2530 non-null   float64
 10  Product_Category_3          2534 non-null   float64
 11  Purchase                    5000 non-null   int64
dtypes: float64(2), int64(5), str(5)
memory usage: 468.9 KB

In [8]:
df1.describe()

,User_ID,Occupation,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
count,5.000000e+03,5000.000000,5000.000000,5000.000000,2530.000000,2534.000000,5000.0000
mean,1.000503e+06,10.106800,0.489200,10.491600,10.309486,10.507893,10237.0926
std,2.868070e+02,6.032037,0.499933,5.732059,5.752187,5.783205,5645.1649
min,1.000001e+06,0.000000,0.000000,1.000000,1.000000,1.000000,504.0000
25%,1.000256e+06,5.000000,0.000000,5.000000,5.000000,5.000000,5386.2500
50%,1.000502e+06,10.000000,0.000000,11.000000,10.000000,11.000000,10330.5000
75%,1.000750e+06,15.000000,1.000000,15.000000,15.000000,15.000000,15045.2500
max,1.001000e+06,20.000000,1.000000,20.000000,20.000000,20.000000,19997.0000

In [10]:
df1.shape

(5000, 12)

In [ ]:
df1.drop(['New'], axis=1, inplace= True) //to drop column
//axis= 1 means column and axis=0 means rows
//inplace=True means any changes or modification made by the organization are applied to the original datagrame or series

In [12]:
df1['Gender'] = df1['Gender'].map({'F':0,'M':1})

In [13]:
df1.tail()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
4995,1000821,P151902,1,26-35,7,C,4+,0,5,3.0,12.0,3786
4996,1000899,P879597,0,0-17,14,B,4+,1,13,NaN,NaN,16071
4997,1000969,P852461,0,36-45,8,C,0,1,17,4.0,NaN,4449
4998,1000709,P466662,0,26-35,9,B,0,0,5,NaN,NaN,8266
4999,1000921,P833754,0,26-35,15,A,3,0,6,NaN,6.0,4794

In [15]:
df1['Age'].unique()

<StringArray>
['36-45', '18-25', '51-55', '55+', '26-35', '46-50', '0-17']
Length: 7, dtype: str

In [16]:
df1_city = pd.get_dummies(df1['City_Category'],drop_first = True)